# Generated by Django 4.2.7 on 2023-12-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=30)),
                ('calificacion', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
